"""
ACRE Engine — Adaptive Cross-Cluster Recommendation Engine
===========================================================
Production module that loads pre-computed artifacts from the data science
pipeline and exposes two functions consumed by the Flask app:

    get_acre_recommendations(tmdb_ids, top_n=5)   → List[int]
    get_baseline_recommendations(tmdb_ids, top_n=5) → List[int]

Artifacts expected (generated by notebooks 02–06):
    Artifacts/feature-engineering/feature_matrix.npy
    Artifacts/feature-engineering/movie_index.csv
    Artifacts/clustering/cluster_assignments.csv
    Artifacts/clustering/cluster_centroids.npy
    Artifacts/clustering/clustering_model.joblib
    Artifacts/clustering/pca_model.joblib
    Artifacts/clustering/reduction_method.txt
"""

import os
import numpy as np
import pandas as pd
import joblib
from sklearn.metrics.pairwise import cosine_similarity

# ──────────────────────────────────────────────────────────────────────────────
# Paths (relative to this file)
# ──────────────────────────────────────────────────────────────────────────────
_BASE_DIR = os.path.dirname(os.path.abspath(__file__))
_FEATURE_DIR = os.path.join(_BASE_DIR, "Artifacts", "feature-engineering")
_CLUSTER_DIR = os.path.join(_BASE_DIR, "Artifacts", "clustering")

# ──────────────────────────────────────────────────────────────────────────────
# Global state — loaded once on first import
# ──────────────────────────────────────────────────────────────────────────────
_feature_matrix = None        # (N, 172) full feature space
_feature_matrix_pca = None    # (N, 30)  PCA-reduced feature space
_movie_index = None           # DataFrame: row-aligned with feature_matrix
_cluster_assignments = None   # DataFrame with 'id' and 'cluster' columns
_cluster_centroids = None     # (K, 30) centroids in PCA space
_pca_model = None             # Fitted PCA transformer
_reduction_method = None      # "pca" | "umap" | "none"
_tmdb_to_row = {}             # TMDB id → feature-matrix row index
_cluster_to_rows = {}         # cluster label → list of row indices
_is_loaded = False


def _load_artifacts():
    """Load all pre-computed artifacts into memory (called once)."""
    global _feature_matrix, _feature_matrix_pca, _movie_index
    global _cluster_assignments, _cluster_centroids
    global _pca_model, _reduction_method
    global _tmdb_to_row, _cluster_to_rows, _is_loaded

    if _is_loaded:
        return

    print("[ACRE Engine] Loading artifacts …")

    # ── Feature matrix (N × 172) ─────────────────────────────────────────
    _feature_matrix = np.load(os.path.join(_FEATURE_DIR, "feature_matrix.npy"))
    print(f"  Feature matrix : {_feature_matrix.shape}")

    # ── Movie index (row ↔ TMDB id mapping) ──────────────────────────────
    _movie_index = pd.read_csv(os.path.join(_FEATURE_DIR, "movie_index.csv"))
    print(f"  Movie index    : {len(_movie_index)} movies")

    # Build fast lookup: TMDB id → row index
    for row_idx, tmdb_id in enumerate(_movie_index["id"].values):
        _tmdb_to_row[int(tmdb_id)] = row_idx

    # ── Cluster assignments ──────────────────────────────────────────────
    _cluster_assignments = pd.read_csv(
        os.path.join(_CLUSTER_DIR, "cluster_assignments.csv")
    )

    # Build cluster → row-indices lookup
    for row_idx, cluster_label in enumerate(_cluster_assignments["cluster"].values):
        _cluster_to_rows.setdefault(int(cluster_label), []).append(row_idx)
    print(f"  Clusters       : {len(_cluster_to_rows)} clusters")

    # ── Cluster centroids (K × D_reduced) ────────────────────────────────
    _cluster_centroids = np.load(
        os.path.join(_CLUSTER_DIR, "cluster_centroids.npy")
    )
    print(f"  Centroids      : {_cluster_centroids.shape}")

    # ── Dimensionality reduction model ───────────────────────────────────
    reduction_path = os.path.join(_CLUSTER_DIR, "reduction_method.txt")
    _reduction_method = open(reduction_path).read().strip()
    print(f"  Reduction      : {_reduction_method}")

    if _reduction_method == "pca":
        _pca_model = joblib.load(os.path.join(_CLUSTER_DIR, "pca_model.joblib"))
        # Pre-compute PCA-transformed feature matrix for fast similarity lookups
        _feature_matrix_pca = _pca_model.transform(_feature_matrix)
        print(f"  PCA matrix     : {_feature_matrix_pca.shape}")
    elif _reduction_method == "umap":
        _pca_model = joblib.load(os.path.join(_CLUSTER_DIR, "umap_model.joblib"))
        _feature_matrix_pca = _pca_model.transform(_feature_matrix)
        print(f"  UMAP matrix    : {_feature_matrix_pca.shape}")
    else:
        # No dimensionality reduction — use the original feature space
        _feature_matrix_pca = _feature_matrix
        print("  No reduction   : using full feature space")

    _is_loaded = True
    print("[ACRE Engine] Ready.\n")


# ──────────────────────────────────────────────────────────────────────────────
# Helper functions
# ──────────────────────────────────────────────────────────────────────────────

def _resolve_rows(tmdb_ids):
    """Convert a list of TMDB IDs to feature-matrix row indices.

    Returns (valid_row_indices, valid_tmdb_ids) — items not found in the
    movie index are silently skipped.
    """
    rows, ids = [], []
    for tid in tmdb_ids:
        tid = int(tid)
        if tid in _tmdb_to_row:
            rows.append(_tmdb_to_row[tid])
            ids.append(tid)
    return rows, ids


def _compute_user_centroid(row_indices):
    """Build a weighted centroid in the *reduced* feature space.

    Weights are the normalised vote_average values of the selected movies,
    so higher-rated picks carry more influence.
    """
    vectors = _feature_matrix_pca[row_indices]

    # Grab vote_average for the selected rows
    weights = _movie_index.iloc[row_indices]["vote_average"].values.astype(float)

    # Normalise weights so they sum to 1
    weight_sum = weights.sum()
    if weight_sum == 0:
        weights = np.ones(len(weights)) / len(weights)
    else:
        weights = weights / weight_sum

    # Weighted mean
    centroid = np.average(vectors, axis=0, weights=weights)
    return centroid.reshape(1, -1)  # (1, D) for sklearn compatibility


def _assign_cluster(user_centroid):
    """Find the closest cluster centroid (Euclidean) and return its label."""
    distances = np.linalg.norm(_cluster_centroids - user_centroid, axis=1)
    return int(np.argmin(distances)), distances


# ──────────────────────────────────────────────────────────────────────────────
# Public API
# ──────────────────────────────────────────────────────────────────────────────

_N_NEIGHBORING_CLUSTERS = 5   # search 5 neighboring clusters
_MOVIES_PER_CLUSTER = 3       # pick top 3 from each → 15 total


def get_acre_recommendations(tmdb_ids, top_n=15, exclude_ids=None):
    """ACRE cross-cluster recommendation.

    Returns movies interleaved round-robin across neighboring clusters so
    that every batch of 5 contains one movie from each cluster:
        [cluster_A #1, cluster_B #1, cluster_C #1, cluster_D #1, cluster_E #1,
         cluster_A #2, cluster_B #2, cluster_C #2, cluster_D #2, cluster_E #2,
         cluster_A #3, cluster_B #3, cluster_C #3, cluster_D #3, cluster_E #3]

    Parameters
    ----------
    tmdb_ids : list[int]
        TMDB movie IDs the user selected (3-5 movies).
    top_n : int
        Maximum number of movie IDs to return (default 15).
    exclude_ids: list[int]
        TMDB movie IDs to strictly exclude from recommendations.

    Returns
    -------
    list[int]
        Recommended TMDB movie IDs in interleaved cluster order.
    """
    _load_artifacts()

    row_indices, valid_ids = _resolve_rows(tmdb_ids)
    if not row_indices:
        return []

    # Step 1 — User preference centroid (reduced space)
    user_centroid = _compute_user_centroid(row_indices)

    # Step 2 — Assign user to a cluster
    user_cluster, distances = _assign_cluster(user_centroid)

    # Step 3 — Rank neighbouring clusters by distance (exclude user's own)
    sorted_cluster_indices = np.argsort(distances)
    neighboring_clusters = [
        int(c) for c in sorted_cluster_indices if int(c) != user_cluster
    ]

    total_clusters = len(_cluster_centroids)
    n_neighbors = min(_N_NEIGHBORING_CLUSTERS, total_clusters - 1)
    neighboring_clusters = neighboring_clusters[:n_neighbors]

    # Step 4 — Cross-cluster retrieval: get top movies per cluster
    selected_set = set(valid_ids)
    if exclude_ids:
        selected_set.update(int(x) for x in exclude_ids)

    per_cluster_ranked = {}  # cluster_id → ordered list of tmdb_ids

    for cluster_id in neighboring_clusters:
        cluster_rows = _cluster_to_rows.get(cluster_id, [])
        if not cluster_rows:
            continue

        # Filter out user-selected movies
        candidate_rows = [
            r for r in cluster_rows
            if int(_movie_index.iloc[r]["id"]) not in selected_set
        ]
        if not candidate_rows:
            continue

        # Cosine similarity between user centroid and candidate vectors
        candidate_vectors = _feature_matrix_pca[candidate_rows]
        sims = cosine_similarity(user_centroid, candidate_vectors).flatten()

        # Sort by similarity descending, keep top _MOVIES_PER_CLUSTER
        ranked = sorted(zip(candidate_rows, sims), key=lambda x: x[1], reverse=True)
        per_cluster_ranked[cluster_id] = [
            int(_movie_index.iloc[r]["id"]) for r, _ in ranked[:_MOVIES_PER_CLUSTER]
        ]

    # Step 5 — Interleave round-robin across clusters
    interleaved = []
    explanations = {}
    
    # Pre-calculate generic explanations based on cluster proximity
    for cluster_id in neighboring_clusters:
        picks = per_cluster_ranked.get(cluster_id, [])
        for tid in picks:
            explanations[tid] = (
                "ACRE identified this movie in a neighboring preference cluster. "
                "While outside your immediate 'bubble', it shares high-dimensional feature "
                "patterns with your favorites, facilitating intelligent exploration into adjacent genres."
            )

    for round_idx in range(_MOVIES_PER_CLUSTER):
        for cluster_id in neighboring_clusters:
            picks = per_cluster_ranked.get(cluster_id, [])
            if round_idx < len(picks):
                interleaved.append(picks[round_idx])

    return interleaved[:top_n], explanations


def get_cluster_description(cluster_id):
    """Generate a descriptive label for a cluster based on its top genres."""
    _load_artifacts()
    if cluster_id not in _cluster_to_rows:
        return "Mixed Genre"

    row_indices = _cluster_to_rows[cluster_id]
    genre_counts = {}
    for r in row_indices:
        genres = str(_movie_index.iloc[r]["genres"]).split(",")
        for g in genres:
            g = g.strip()
            if g:
                genre_counts[g] = genre_counts.get(g, 0) + 1

    # Get top 3 genres
    top_genres = sorted(genre_counts.items(), key=lambda x: x[1], reverse=True)[:3]
    if not top_genres:
        return "General Interest"

    return ", ".join([g for g, _ in top_genres])


def get_acre_explanation(recommended_tid, user_tmdb_ids):
    """Generate a detailed explanation for an ACRE recommendation."""
    _load_artifacts()

    # Get user's cluster
    row_indices, _ = _resolve_rows(user_tmdb_ids)
    user_centroid = _compute_user_centroid(row_indices)
    user_cluster, _ = _assign_cluster(user_centroid)
    user_desc = get_cluster_description(user_cluster)

    # Get recommended movie's cluster
    if recommended_tid not in _tmdb_to_row:
        return "Recommended based on cross-cluster similarity to your taste profile."

    rec_row = _tmdb_to_row[recommended_tid]
    rec_cluster = _cluster_assignments.iloc[rec_row]["cluster"]
    rec_desc = get_cluster_description(rec_cluster)

    return (
        f"Your profile aligns with the '{user_desc}' preference group. "
        f"We found this movie in the neighboring '{rec_desc}' cluster. "
        f"It offers a bridge from what you usually enjoy into related thematic territory."
    )


def get_baseline_recommendations(tmdb_ids, top_n=15, exclude_ids=None):
    """Baseline same-cluster recommendation.

    Parameters
    ----------
    tmdb_ids : list[int]
        TMDB movie IDs the user selected.
    top_n : int
        Maximum number of movie IDs to return (default 15).
    exclude_ids: list[int]
        TMDB movie IDs to strictly exclude from recommendations.

    Returns
    -------
    list[int]
        Recommended TMDB movie IDs from the user's own cluster,
        ranked by cosine similarity to the user centroid.
    """
    _load_artifacts()

    row_indices, valid_ids = _resolve_rows(tmdb_ids)
    if not row_indices:
        return []

    # Step 1 — User preference centroid
    user_centroid = _compute_user_centroid(row_indices)

    # Step 2 — Assign user to cluster
    user_cluster, _ = _assign_cluster(user_centroid)

    # Step 3 — Retrieve movies from the same cluster
    cluster_rows = _cluster_to_rows.get(user_cluster, [])
    selected_set = set(valid_ids)
    if exclude_ids:
        selected_set.update(int(x) for x in exclude_ids)

    candidate_rows = [
        r for r in cluster_rows
        if int(_movie_index.iloc[r]["id"]) not in selected_set
    ]
    if not candidate_rows:
        return []

    # Step 4 — Rank by cosine similarity to user centroid
    candidate_vectors = _feature_matrix_pca[candidate_rows]
    sims = cosine_similarity(user_centroid, candidate_vectors).flatten()

    ranked = sorted(
        zip(candidate_rows, sims), key=lambda x: x[1], reverse=True
    )

    return [int(_movie_index.iloc[r]["id"]) for r, _ in ranked[:top_n]]
